<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = ["Yayasan Pendidikan Islam Miftahul Hidayah",
            "Adian Latifa Nurrohman",
            "Rumah Zakat Kalimantan Selatan",
            "Yayasan Ummu Aisah Terpadu",
            "Tabungan Surga",
            "Gimmy yaliandra",
            "Huni Foundation",
            "Yayasan Berbagi Kasih Mulia TTS",
            "Rumah Yatim Jawa Tengah",
            "FILANTRA OFFICIAL",
            "Muhammad wafa aldiansyah",
            "MOHAMMAD NIZAR",
            "siti Suriani",
            "Yayasan Bina Semesta Mandiri",
            "Darul Huffadz Mendala",
            "Yayasan Peka Peduli Sulawesi",
            "Hans",
            "Sahabat Bekantan Indonesia",
            "Rumah Zakat DKI Jakarta",
            "PEMUDA PEDULI SESAMA UMAT",
            "Romeo Allan Sumardi",
            "YAYASAN PANTI ASUHAN AL HIDAYAH",
            "YAYASAN GARUDA MANDIRI PEDULI",
            "Yayasan Bahagia Berbagi Indonesia",
            "Willy Heriono",
            "Mugis",
            "Danial SH",
            "YBM Hasuna",
            "Darul Hijrah Peduli",
            "Yayasan Orang Desa",
            "Praditya Salim",
            "Yang Jeongin Indonesia",
            "Rina Marlina",
            "DAI PEDULI",
            "Udi Santosa",
            "Sedekah Berkah",
            "Israwardani",
            "YOI Indonesia",
            "Bambang Supriyanto",
            "Achmad Thoriq",
            "Tanmia Peduli",
            "YAYASAN DARUL HIKAM",
            "BUAH HATI FAMILY",
            "Yasir Suardi, S.Pd",
            "IDRIS MOH YASIN",
            "Raja Muhammad Innamul Hasan",
            "Untuk Teman",
            "deon ucup",
            "Yayasan Panembahan Gunung Jati",
            "Fera fauziyah",
            "Livingseas Indonesia",
            "MTS Darussalam",
            "Relawan Nusantara",
            "Yayasan Baitur Ridwan Al Islami",
            "Nida ul Husnayaini",
            "Ujang sulaeman",
            "MANIS PEDULI",
            "Al Bahjah Barat",
            "Amal Baik Insani",
            "Respek Peduli Lampung",
            "Asar Humanity Aceh",
            "Daniel Ferari Simanjuntak",
            "Made Widhya Widjajaprana",
            "Rida",
            "Basecamp Solidaritas Indonesia",
            "anis banowati",
            "ALI ASHADI",
            "sadulur alam",
            "Yayasan Proyek Peduli Indonesia",
            "Gunawan Ahmad",
            "Al Fatihah",
            "Boen San david",
            "Sajiwa Foundation",
            "Yayasan Hudal Lin Naas",
            "pantiasuhan ikhlas CintaKasih Indonesia",
            "Raden Jatnika",
            "Yayasan Pondok Al Quran Dusturuna",
            "ERVINNA",
            "solehudin",
            "Ishak Wahyudi",
            "Dian Arifah",
            "Saekoni Anhar",
            "Rumah Kitabisa",
            "Yayasan Harapan Sumba",
            "Yayasan Bendega Alam Lestari",
            "Wakaf Produktif",
            "Muhamad Haekal Ridho",
            "Bantu Teman Sumatera",
            "Selmadena",
            "Lukman Nurhakim",
            "Robert Kenedy Diaz",
            "Bayu Pamungkas",
            "nur ilham",
            "Yayasan Baburrahman",
            "Asih Bumi Insani",
            "Shelter Orza Animals",
            "LBH BALI",
            "Chanee Kalaweit",
            "Derris Surya",
            "Penghubung Amanah Donatur Indonesia",
            "Yayasan Cinta Kemanusiaan Gorontalo",
            "Katolik Media",
            "Jiwanto simanungkalit",
            "Achmad Rafee'ur Ruziq",
            "ERNAWATI",
            "Yayasan Setia Memberi Sesama",
            "Ena rusmana",
            "YAYASAN KITA PEDULI RUMAH SEHAT",
            "Muhammad Ichsan Abda",
            "YAYASAN SOSIAL BINA UMAT ALMISYKAH",
            "Rumah Yatim",
            "Infaq Berkah Qurani",
            "SIDIK SULAKSANA",
            "Cakra Abhipraya Responsif",
            "Mustofa",
            "Yayasan Pendidikan Islam Al-Hidayah",
            "Anjas karwiyanto",
            "Restu",
            "Mari Bantu",
            "Mangkera For Maluku",
            "ISTANA YATIM Yayasan Darul Ilmi Al Fikri",
            "Pusat Studi Al-Quran",
            "Abdul Rahman",
            "Yayasan Sunan Bonang",
            "Yayasan Harapan Umat Indonesia",
            "Nur Setyoningsih, S.Kom",
            "MOHAMMAD HANADZIL SH",
            "Intan M Sukarna",
            "Delina Juni Artha Lubis",
            "Muhamad David Sunairi",
            "Yayaysan Peduli Dan Berbagi",
            "Baitul Mall Hidayatullah Maros",
            "RAMBU ASANA",
            "Relawan Bekantan Indonesia",
            "Taufik Hidayat",
            "Rumah Zakat DIY",
            "Yayasan Nurul Fahmi",
            "Sedekah subuh santri Yatim dzuafa penghafal Alquran",
            "PANTI ASUHAN TAHFIDZ KHOSYATILLAH",
            "Yunika Wardhani",
            "Mohamad Roland Zakaria",
            "Moch Agung",
            "Sinergi Kebaikan Ummat",
            "Nurlaily Irfa Zuhriana",
            "Yayasan Nurul Huda Gumelar",
            "Saling Membantu",
            "Rumah Zakat",
            "Mahdi Muntadzor",
            "Butiran Debu",
            "heri kinayung",
            "AHMAD MUSANNA",
            "Nina Nafisah",
            "Romelyn Frans Yoseph",
            "David adimas",
            "Muhammad reza bagus aryanto",
            "Sri massrifah",
            "suhendri",
            "afrizal",
            "Sedekah subuh panti asuhan",
            "Dermawan Surya Kencana",
            "MERAWAT INDONESIA",
            "Maftuhatunnisak",
            "Theresia Ngutra",
            "Sedekah subuh",
            "Cancer Support Kuningan",
            "Melinda T",
            "Masjid Nusantara",
            "Yayasan Suara Hati",
            "Awaluddin Paliliran",
            "Amal Bakti Dunia Islam",
            "feri lens",
            "Asar Humanity DIY",
            "LinkAja",
            "Pondok Pesantren Alkautsar Cilawu",
            "Dendi Nurwega",
            "Purwaningsih",
            "FoodCycle Indonesia",
            "Lombok's Charity",
            "Suisdiyono",
            "Syifa Rochati",
            "Shima Tejawati",
            "Pondok Pesantren Tahfidzul Qur'an",
            "Elmansyur Peduli",
            "Yayasan Islam Al Yamin Kudus",
            "YAYASAN ASHSHIRATHAL MUSTAQIM PANGKEP",
            "SAPA Regional Tasikmalaya",
            "Wahyu Hermawan",
            "Gerakan Peduli Indramayu",
            "Milenial Babel Peduli",
            "Jabodetabekinfo Peduli",
            "Equivalent Pangasi",
            "Sedekah Masjid",
            "Yayasan Minang Care Indonesia",
            "Khosti Yerson",
            "UPZ Kitabisa - BAZNAS",
            "Akhmad Surya Siregar",
            "Dompet yatim dhuafa",
            "Mukti Aris",
            "Gerakan Gemar Sedekah",
            "YAYASAN KARYA ILAHI MAUMERE",
            "Bagus setiono aji",
            "Siti Nurul",
            "Agus Tri Purnomo",
            "Endang Aguswati",
            "Gabriella soraya situmorang",
            "Yayasan Aksi Insan Nusantara",
            "YAYASAN SAHABAT MUSTAHIQ SEJAHTERA",
            "Supardi",
            "Ridho Pratama",
            "Wuri Annisa",
            "Yayasan Sahabat Ayah Sarah",
            "Sedekah Subuh Yatim Dhuafa",
            "LBQ Risalatuna Jakarta",
            "Bagus Aji Santoso",
            "Yayasan Awiyah Tsaniyah",
            "Muhammad Elya Isman",
            "Frekuensi Indonesia",
            "YSKI Sumatera",
            "FAHIJMA NATURE INDONESIA",
            "Siaga Peduli",
            "Sendi lesmana",
            "Panti Asuhan Kasih Murni Teladan Medan",
            "RUMAH QURAN ELTAHFIDZ QU",
            "Yayasan Rute Langkah Amanah",
            "Yayasan Konservasi Alam Nusantara",
            "Yayasan Misykat Cahaya Ilahi",
            "SODAQOH AMANAH",
            "RONI SALMON DEPARI",
            "Ilyas",
            "Baitul Izzah",
            "ICHA LINTANG RESTIKA",
            "Andri Agustia",
            "Khoyrunnisa",
            "Fauji",
            "Vhira Fujita",
            "Yayasan Gerakan Mengajak Sedekah",
            "LAZ Masjid Raya Bintaro Jaya",
            "Lazismu IBM Bekasi",
            "mutiara rindang indonesia",
            "Riha Azharina",
            "Hmoch Sumari, Sp",
            "bismillah",
            "Yayasan Bhakti An Nisa",
            "Yayasan Anak Sholeh 85",
            "Mokhamad Nur Zaman",
            "Yayasan Rumah Peduli Annisa",
            "Gowes Kebaikan",
            "Ayu puspita sari",
            "YAKESMA Nusa Tenggara Barat",
            "Badan Amil Zakat Nasional",
            "Bentang Kalimantan Tangguh",
            "Diana Novita",
            "Abdul Mujib",
            "Yayasan Gugus Karya Mandiri",
            "Kitabisa",
            "Yayasan Sayangi Dhuafa",
            "Yayasan Sayap Ibu Banten",
            "Sigit Satriawan",
            "Fyurith Andrianto Irda",
            "TAHFIDZUL QURAN HALIMAH ASSADIYAH",
            "Yayasan Pondok Pesantren Darul Amanah",
            "Yayasan Alfalah Biru Satu",
            "Batara Samudera Fahmianto",
            "Pondok Pesantren Modern Hidayatullah Mario",
            "Rumah Zakat Jayapura",
            "Masyuhdi",
            "Yayasan Jati Adulam Ministry",
            "RAHMAT PRIANTO",
            "Yayasan Sahabat Masjid",
            "Human Initiative",
            "Yayasan Darul Huda",
            "Ummi Haniek Mainingrum",
            "Misbah ucok",
            "YAYASAN CINTA HARAPAN INDONESIA",
            "Centre for Orangutan Protection",
            "Yayasan LBQ Risalatuna",
            "Annis hannafiah",
            "Anggina Sari",
            "Gemaku Foundation",
            "M Ismail Zuhri",
            "Baitul Maal Hidayatullah",
            "Lembaga Peduli Dhuafa",
            "Senyum Desa Koordinator Wilayah Lombok",
            "Yayasan Zohara Kasim Hasan",
            "Syafrizal",
            "Yayasan At Taubah Islamiah Terpadu Garut",
            "UPZ Yayasan Insan Mulia Berbagi",
            "Hyuka Project Indonesia",
            "Yayasan Riyaadlul Barokah",
            "Yayasan Rumah Impian Indonesia",
            "Warung Sedekah Lamongan",
            "Ajie Pangestu",
            "Budi Riyanto Foundation",
            "Diaspora Qatar",
            "BAZNAS Hub",
            "lmi ngawi",
            "Yayasan Pontren Yatim Fathul Islam",
            "Laskar Hijau",
            "ANISA",
            "muhammad fanani",
            "Yayasan Mahad Al Islami Arrohimiyyah",
            "PPTQ ALFATAH KAMPAR",
            "Yayasan Peduli Kasih KNDJH",
            "Fajar Tri Anggono",
            "Brave Cat",
            "pokdarwis Ujung Kulon",
            "Annisa Mayadewi",
            "ERVYN GESANG PRAKOSO",
            "BUDIMAN",
            "Elisabeth Noviana Femiyanti Marsita",
            "Alshad Kautsar Ahmad",
            "Erfian Asafat",
            "Mar'atus Sholikhah",
            "robby wahyu firmansyah idris",
            "Hengky Ade Putra",
            "ESTER ARYNY CHANDRA",
            "Dompet Dhuafa Sulsel",
            "Rengganis Indonesia Foundation",
            "Hasbi Peduli",
            "Hafiid Ramdhani Pratama",
            "Rudi setya purnomo",
            "LAZIS MUHAMMADIYAH",
            "Livia Florencia",
            "Sigit Wicaksono",
            "YAYASAN BOLLEN FLORES",
            "Yayasan Hidaytus Salam Al Islamy",
            "Cinta Abi Ummi",
            "Yayasan Bina Insan Indonesia",
            "Yayasan Mihrab Quran",
            "Mamat Rahmat",
            "sedekah subuh panti asuhan",
            "Sonitus Caeli Youth Choir",
            "Kerabat Yatim dan Dhuafa",
            "Asep Mohamad Mutaqin",
            "Badan Wakaf Al Quran",
            "Sunaryo Haryo Bayu",
            "Yayasan Baitul Yataama Fadlan",
            "Yayasan Mizwan Ainul Yakin",
            "LAZ UMMUL QURO BOGOR",
            "Maymunah",
            "Rumah Harapan",
            "Putri Ayu Sandra Dewi",
            "Cinta Quran Foundation",
            "Yayasan Samalas Tresne Gumi",
            "Saefudin Syafi'i",
            "Yayasan Yatim Darut Tholibin",
            "Panitia Pembangunan Masjid Darussalam Desa Lamahoda NTT",
            "Rumah Yatim Kalimantan Selatan",
            "MAKSONAH",
            "Yayasan Jakarta Amanah",
            "PUSH CHARITY",
            "Ari Irfan Hariri",
            "Maria Sariyanti",
            "ISCP(Indonesian Species Conservation Program)",
            "Abdullah Efendy",
            "Riski Nur Sarifah",
            "Adi Cahyadi",
            "abdul ghofur",
            "Teman Kecil",
            "PEDULI WARGA BALIKPAPAN",
            "Roy Murtadho",
            "Syaiful akhyar laitupa",
            "William Gunawan",
            "Life For Ummah",
            "Taofik Hidayatulloh",
            "Yayasan Ponpes Raudhatul Azhar",
            "Earth Hour Indonesia",
            "DKM Masjid Syuhada",
            "Dewi Masruroh",
            "Diaspora Taiwan 1",
            "Adam Fabumi Foundation",
            "Yayasan Dana Sosial Al Falah Peduli",
            "Fathul alim",
            "Ayi miftahul parhi S.Pd",
            "International Networking for Humanitarian INH",
            "Yayasan Masjidku Digital Indonesia",
            "Bang Yossi",
            "Nurul ingsan bil mustofa",
            "Yayasan Kampung Quran Abu Darda",
            "Retno Audite Dwiastini",
            "Yeni Tanaka",
            "Nifah",
            "AAT",
            "Siska Nirmala Puspitasari",
            "Bantu Teman Indonesia",
            "Shelter Pak Johan(Yayasan Dunia Satwa Indonesia)",
            "Amal Sosial Odesa",
            "Yayasan As sajad Kebonagung",
            "Yayasan Islam Madinah Tolitoli",
            "Yayasan Insan Tebuireng Tegal",
            "Semerbak Berbagi Komuniti",
            "Oktian Jaya Wiguna",
            "Rumah Yatim Yogyakarta",
            "Yayasan Bali Bersih",
            "Yayasan FMR",
            "Hie Alun",
            "Ma'had Islam Rafiah Akhyar",
            "Aldi Muhamad Fahrezi",
            "Rumah Tahfidz Yatim Dhuafa",
            "Auro Mireqal Center",
            "YAYASAN DAARUL HAMID ASSALAM",
            "Yayasan PAPI",
            "Abela Ridma Oktavia",
            "Fathurrachman",
            "Zakatku Bakti Persada",
            "Nurainisyah",
            "Anan",
            "Yani Dewi Susanti",
            "Sismawanto",
            "RQV Indonesia",
            "Akmal Astani",
            "Stevani martio",
            "MUHAMMAD ROSSY RAMADHANI",
            "MUHTAR SAFAAT",
            "BAITUL HAMDI",
            "Iwan ridwan",
            "Perhimpunan Pelestarian Burung Liar Indonesia",
            "SURYADI",
            "Wujudkan Mimpi",
            "WALIY SUGMA",
            "Ansori",
            "fitria dwi astuti",
            "hasriani hasyim",
            "LAZ RYDHA - Rumah Yatim Dhuafa",
            "Wahana Visi Indonesia",
            "Sastra Dewantara",
            "Sedekah membawa berkah",
            "Susilawati",
            "ISNA SIFA",
            "Awang kelana",
            "Yayasan Kabua Dana Rasa",
            "S Z",
            "IAR Indonesia",
            "Bantu Hewan Terlantar Yuk",
            "Syarifah Aisyatirradiyah",
            "Chris Januardi",
            "Risma Ulpiyana Maulida",
            "Yayasan Fath Qurani Center",
            "MiaSyifa Cancer Care",
            "IRHAMUL FIKRI",
            "Yayasan Sahabat Kebahagiaan Indonesia",
            "Yayasan Darul Karim Semarang",
            "Salam Setara Amanah Nusantara",
            "Yayasan Griya Qur'an Difabel",
            "Rachmat Adhiputra Kusumah",
            "Wawan Hermawan",
            "Yayasan KAKI KOTA",
            "Yayasan UMMI",
            "Aksi Insan Mulia",
            "Panti Asuhan Yayasan Hidayatullah Kalbar",
            "Aat Sumarna",
            "YATIM DZUAFA PENGHAFAL ALQUR'AN",
            "ABDUL ROZAQ",
            "Yayasan Darul Falah Al-Hasyimiyah",
            "Yayasan Mufakat Albanna Indonesia Jawa Barat",
            "Endang Sutrisnowati",
            "Rini Indriani",
            "Rohmatul Umah",
            "YAYASAN YATIM MADANI",
            "Jabar Quick Response",
            "yayasan nurul fadilah pasirwangi kidul",
            "Yayasan Centre Plus HU Jawa Barat",
            "Sekolah Relawan",
            "Yayasan ahbaabul mukhtar",
            "ZULKIPLI",
            "Aji Saras Wanto",
            "Yayasan Rumpun Anak Pesisir",
            "Hidayat",
            "GENERASI RABBANI",
            "GORONTALO BAIK INDONESIA",
            "Lembaga Pelita Harapan",
            "Paulanda Timotius P Siahaan",
            "Pondok Quran Wakaf",
            "Alizzah Peduli",
            "Brand Partnership Kitabisa",
            "Roudotul Amanah",
            "Yayasan attasyrif warrohman",
            "Eko Prayogo",
            "Adham Wira",
            "YAYASAN KYAI AGENG SELO",
            "Bella Saputri",
            "Agus Sukmana",
            "Sedekah Subuh Panti Asuhan",
            "Indonesia Mengajar",
            "Yayasan Al Bukhori Murtajih",
            "Mia Nur Fatimah",
            "Sinergi Filantropi",
            "Ahmad Ridho Firmansyah",
            "Ana silfiyatur rohmaniyah",
            "Global Sedekah Movement",
            "Peduli Hewan Sekitar",
            "ECOTON FOUNDATION",
            "NUR KHASANAH",
            "Abu Hasan",
            "Rosyanti",
            "Ziardi Achmad",
            "Agung Cahaya Wibowo",
            "Yatim Madinatulhaq",
            "Yayasan Usrotunnur Zainul Hayah",
            "Maskanul Huffadz",
            "Rio arisandes hasugian",
            "LKS Apik Mandiri",
            "Hamdan aprian",
            "Murni Umairoh",
            "Sahabat Kristiawan Peduli",
            "Novita Yulianti",
            "5201032610020001",
            "Zubaidah",
            "YAYASAN PAUD KB SEHAT",
            "Serambi Gotong Royong",
            "Ignasius Paulo Datoalin",
            "Medical Partnership Kitabisa",
            "Maria Sulistyo Rini",
            "Inda Dewi",
            "Ragil faturrohman tohir",
            "Yayasan Bangun Sinergi Umat",
            "Retno Watini",
            "yayasan galang bersama kami",
            "Pondok Sedekah Indonesia",
            "Wujud Aksi Nyata",
            "AHMAD ZAENAL ARIFIN",
            "Sahabat Gotong Royong",
            "Saktiadi Wibawa",
            "Widiyani Srimumpuni,S.PD",
            "Sedekah Subuh Rumah Tahfidz Yatim",
            "HMA PPM",
            "MAYLATUR ROFIKOH",
            "Maya Soeripto",
            "Putu Pesa Nugraha",
            "Komunitas Kantong Doraemon",
            "Fitri sugianti",
            "Hendik Pujiyanto",
            "MUHAMAD ROJI",
            "Hasannudin",
            "Muhammad kholiq",
            "Panti asuhan sunan kalijaga",
            "Yayasan Al-Amanah Nusantara",
            "Ilman nafi'",
            "Dompet Yatim dan Dhuafa",
            "Ma'had Madinatul Qur'an",
            "Dedy Juliadi Nasution",
            "HANDRY FAHMY MUZAHAR",
            "Yayasan Pondok Pesantren Mamba'ul Bayan NW",
            "Yayasan Bumi Santri Arrumi",
            "YAYASAN ASH SHOFIA",
            "WakafCendekiaIndonesia",
            "Ni Kadek Septiani",
            "Sahabat Berbagi",
            "Literasi Lumbung Foundation",
            "Yayasan Munashoroh Indonesia (YMI)",
            "Arif Mahendra",
            "Ayodya Wisnu Wardana",
            "Yayasan Lembaga Pendidikan Islam Sumurboto AlFattah",
            "Indra Adikusuma",
            "Yayasan Alamanda",
            "Leni Kusdiani Apriani",
            "Rumah Tahfidz Madain",
            "Barracuda Diving Club",
            "Harapan Amal Mulia",
            "fajar indra yoga",
            "LAZ DASI NTB",
            "Rumah Tahfidz Yatim",
            "MUKH RIVALDI MUFTI WIBOWO",
            "Dompet Dhuafa Maluku",
            "Rachel vilie",
            "Senyum Kita Foundation",
            "Hutan itu Indonesia",
            "Rahmat Saputra",
            "Dompet Sosial Madani",
            "YAYASAN GEMA INSAN AMANAH",
            "Yayasan Nurul Anwar Syihab",
            "MASJID ULIL ALBAB UII",
            "Yuk Peduli",
            "Yayasan Sam'an Netra Mulia Berkah",
            "Amelia Febiani",
            "Yuli",
            "The Charity of Almuhibbin",
            "I KETUT SUBAGIA",
            "Yayasan Remagi Bali",
            "Ali Mundlofir",
            "Anggita Dian Cahyani",
            "Elly Satjawidjaja",
            "Soffa Sagara Bagja Jamin",
            "Yayasan Danielle",
            "RIKO ADI SAPUTRO",
            "Sedekah Subuh Infaq Pangan Untuk Ratusan Yatim Piatu",
            "ZAHRA",
            "Andi Arisman, S.Pd",
            "Panti Asuhan LKSA Nurul Ihsan",
            "JUNAS",
            "Sahabat Pedalaman",
            "Nurul Fitriani Badriyah",
            "sedekah subuh untuk lksa kyai ageng",
            "Asrizal",
            "LAZ NAHWANUR",
            "Arham Hafiz Ridani",
            "BangroniX Peduli",
            "Sinergi Insani",
            "Sahruldin",
            "MIRHANUDIN",
            "Yayasan Visi Maha Karya",
            "Rumah ZaKat Cirebon",
            "Yayasan Madago Indonesia",
            "Ultrafast Medical Tech",
            "Kausar Adjab Khan",
            "Hablumi Nanas",
            "YAYASAN YPI PONTREN SABIILUNNAJAT",
            "Solar Chapter Official",
            "YAYASAN SAHABAT DHUAFA BANYUWANGI",
            "Panca Olah Institute",
            "respek peduli lebak",
            "darul ikhlas",
            "Yayasan Amanah Sedekah Indonesia",
            "Made Dyah Agustina",
            "Peduli Hewan Liar",
            "Ciwaruga Bina Generasi Muda",
            "Yayasan Darul Husna",
            "Felix Gracianus Setiadi",
            "Ghofur Rozak Aminudin",
            "FALUGOSA GIAWA",
            "Yayasan Lazuardi Indonesia",
            "Natha Satwa Nusantara",
            "FAHMI ABDULLAH",
            "Negeri Untuk Flores",
            "Rumah Amal Salman",
            "Erru barwoto",
            "dPeduli",
            "Yayasan Ruang Pasien Indonesia",
            "Lembaga Amil Zakat Al Aqsha",
            "Al Ikhlas Qurani Tajur",
            "Rumah Zakat Semarang",
            "Rabbanians ID",
            "YAYASAN DAR ATTAQWA WADDA'WAH SMG",
            "Yayasan darul hidayah",
            "LAZARUS",
            "Yayasan Rinjani Bandung",
            "Stefanny",
            "Dompet Kepedulian Muslim",
            "CITRA TRISNAWATI",
            "Sadinda Linda Safitri",
            "Perkumpulan pemerhati lingkungan",
            "Infak dan sedekah panti asuhan",
            "AKHMAD SUHERMAN",
            "Yayasan Kita Mitra Berbagi",
            "Bahagia Berbagi Indonesia",
            "Srianto Sabdi",
            "Diaspora Kuwait 1",
            "AL IKHLAS BANI USMAN",
            "Sarana Berbagi",
            "apik mandiri",
            "Taqiya Quran Care",
            "Aranda Salsabila Amani Ramadhani Hamzah",
            "Yulianty prastica",
            "Aksi Relawan",
            "Yayasan Kreasi Bangun Semesta",
            "Moch ichwan Persada",
            "Paguyuban Sundawani Kab. Bandung",
            "Yayasan nurul iman lemahsugih",
            "Yayasan Sekolah Al Quran",
            "Penghantar Perubahan Indonesia",
            "yunus",
            "Yayasan Dompet Dhuafa Republika",
            "Nur Fadli Alamsyah Nasir",
            "SUPYADIN",
            "Ni Wayan Rahayu",
            "Yayasan Ginjal Indonesia",
            "Gugun Muhammad",
            "Moch Rezky Indrawan Ilham",
            "Bahagia Berbagi Indonesia - Pemalang",
            "Penderma.id",
            "Yayasan Sahabat Peduli Kasih",
            "Gede Bayu Panditanatha",
            "Shidqi Rizqullah",
            "dewi nareswari",
            "Yatim Penghafal Quran",
            "Abd. Rohman",
            "Yayasan Tunas Sehat Indonesia",
            "Yayasan Kebaikan Bantu Sesama",
            "Muhammad Syamsul Hadi",
            "Novita Astri Istiqomah",
            "Yayasan Sahabat Cinta Umat",
            "odik muhamad",
            "BAZIS ANDA",
            "Noor Mila Sari",
            "Yayasan Anugerah Tuhan Hafara",
            "I Komang Sukarma",
            "Dompet Dhuafa Yogyakarta",
            "Yayasan Plan International Indonesia",
            "yayasan islamic",
            "Hadim",
            "Komunitas Pelita",
            "Herifan Setiawan SEI",
            "Rumah Yatim Kalimantan Barat",
            "Maryam Wiana",
            "Setiya Syahbudin",
            "Lazis Tasyrif",
            "Yayasan Mambaul Faizin Al Jafar",
            "Jaka Satria",
            "Diman",
            "Pesona Kebaikan",
            "MOHAMMAD FAHRUDDIN",
            "Lazis Jateng",
            "Yayasan Qosim Al-hadi Semarang",
            "YAYASAN NUR HIDAYAH MANDIRI SEJAHTERA",
            "Yayasan Budi Bakti Mulia",
            "Erika Richardo",
            "Kapiler Indonesia",
            "Marcel Alveri Adis",
            "Yayasan LombokCare",
            "HUNI Foundation",
            "Taufik Akbar",
            "Yayasan Sebaca Indonesia",
            "APRILYA LESTARI",
            "SETYAWATI",
            "Yayasan Dauman Quran",
            "Danu Alfika Nugraha",
            "YATIM MADANI",
            "Agung Okta Fianto",
            "RAN ft Yura Yunita",
            "WAFCAI Yayasan Kursi Roda dan Pusat Persahabatan Asia",
            "Al Khair Indonesia",
            "Baitul Wakaf",
            "LAZ Manajemen Zakat Indonesia",
            "AiKite Indonesia",
            "YAY WWF INDONESIA",
            "BAITULMAAL MUAMALAT",
            "Asep Uup Saepuloh",
            "Rumah Qur'an Ash-Shalihin",
            "Diaspora Oman",
            "Yayasan Bunda Salamah",
            "Yayasan Sayap Proyek Indonesia",
            "Searah Cita Nusantara",
            "Lembaga Cinta Kasih Makassar",
            "Learn Quran",
            "Ali Wirasmara",
            "Nur Khikmah",
            "Peduli Umat",
            "Yayasan MTS Az-Zahra",
            "Rama Riyadi",
            "Suyitno",
            "Berbagi takkan rugi",
            "Syahril Asfari",
            "Panggih Suseno",
            "Feri Rusdianto",
            "Muhamad Gilang Almalik",
            "INISIATIF ZAKAT INDONESIA",
            "Rumah Zakat Solo",
            "Abrar Hamdi",
            "Piter Cahyo Pramono",
            "Baitul Maal itQan",
            "Merina Anindita",
            "Yayasan Futuhal Arifin Al Islamy",
            "Yayasan Literasi Anak Indonesia",
            "Penunggang Kuda Kebaikan",
            "Yayasan Khairunnas Peduli",
            "Sedekah santri yatim dhuafa",
            "Dewi pertiwi",
            "Aminullah Tajuddin Yusuf",
            "Imas Suryani",
            "Griya Yatim dan Dhuafa",
            "Panti Yatim Prima Bakti",
            "Sayang Hewan Liar",
            "Ayu Ms",
            "KL Lazismu Baitul Maal Khairu Ummah",
            "sedekah subuh",
            "Fitri Indriani Dwi Astuti",
            "Zainal Abidin",
            "Yayasan Al Iman Pakenjeng",
            "Yayasan Tunasmuda Care",
            "Zakat Yatim penghafal AlQuran",
            "SADAQA",
            "LMI ZAKAT",
            "Aksi Indonesia Lestari",
            "Yayasan Atmanagari Kusuma Nusantara",
            "Rajin",
            "Indra Jaya",
            "Oei ik hoa",
            "Yayasan Majelis Al Fatih Albaqili",
            "Suliyati",
            "Arief andriatno",
            "Yayasan Dana Sosial Al Falah Jember",
            "Lingkar Peduli Indonesia",
            "Yayasan LTI Care",
            "Ina Yusuf",
            "Masjid Babuttaubah Jor",
            "ASAR Humanity Jakarta",
            "PPM Al Hikmah Nur Hidayah",
            "LAZNAS Dewan Dakwah",
            "Solidaritas Dermawan Indonesia",
            "Erry Novianto",
            "Tanwijaya gunawan",
            "rossi",
            "Daniel Julius",
            "Annisa Muliawati",
            "Muhamad Hadi Irfan",
            "Gusdurian Peduli",
            "Ali Rosidi",
            "Kelvin Surijan",
            "LAZIS NURUL FALAH",
            "William Chandra",
            "Aep Saepudin",
            "Yayasan salman alfarizi",
            "Yayasan Al-Ikhwaniyyah Banyuresmi",
            "Henny Wu",
            "Mego Antoro",
            "Alqodiiri Medalsari Cikijing",
            "Berdaya Foundation",
            "Gadis Tara Vidyarthi, SE",
            "muhammad sholeh",
            "Ulul azmi.As",
            "Mustasim",
            "YAYASAN MUTIARA SURGA",
            "Wakaf Salman ITB",
            "PPPA Daarul Qur'an",
            "Amal Khair Yasmin",
            "Deborah Kurfiss",
            "Syarif",
            "Panti Asuhan Baitul Yatim",
            "YAYASAN SALING BERBAGI KEBAIKAN",
            "YAYASAN GERAKAN KERJA KEMANUSIAAN INDONESIA",
            "Yayasan Panti Yatim Indonesia Al Fajr",
            "Lanny Gunawan",
            "Jamesta Istimewa",
            "Seribu Senyum",
            "BSI Maslahat",
            "Yayasan Islam Igara Pesantren Yatama Asiyah",
            "Andhi Shera Suyono",
            "Yayasan Madinatur Rahmah hidayah",
            "Rotua sari widiastuti siahaan",
            "Mukaromudin",
            "Muhamad Alwan",
            "Fachrurozi",
            "Agus Chandra Sugiharto",
            "Murod Maulana",
            "Bella Bonita",
            "Ayo Bersihkan Laut",
            "Pondok Yatim dan Dhuafa",
            "Darmawan",
            "Heri Eko Wiratno",
            "Amanah Ummah Berbagi",
            "YSDP Nurul Fath",
            "Evita Oktaviani",
            "Mega apriliyanti",
            "rizal andrean",
            "GDSC Indonesia",
        ];

        $new_users = [];
        foreach ($users as $user) {
            $rand_num = substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 5);
            $email = substr(str_replace(" ", "", $user), 0, 5) . $rand_num . "@gmail.com";
            $rand_str = substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 7);
            User::create([
                'name' => $user,
                'email' => $email,
                'password' => Hash::make($rand_str),
                'role' => 'user',
                'metode_registrasi' => (rand(0, 1) == 1) ? 'form' : 'google',
                'verification_success' => (rand(0, 10) < 7) ? true : false,
            ]);
        }
    }
}
